__author__ = 'esteele'

ETHNOLOGUE_SOURCE_ABBREV = "EL"
FIND_A_BIBLE_SOURCE_ABBREV = "FB"
WALS_SOURCE_ABBREV = "WA"
JOSHUA_PROJECT_SOURCE_ABBREV = "JP"

source_abbrev_name_dict = {
    ETHNOLOGUE_SOURCE_ABBREV: "Ethonologue",
    FIND_A_BIBLE_SOURCE_ABBREV: "Find A Bible",
    WALS_SOURCE_ABBREV: "WALS",
    JOSHUA_PROJECT_SOURCE_ABBREV: "Joshua Project"
}

TRANSLATION_STATE_COMPLETE_BOOK = "CB"
TRANSLATION_STATE_NEW_TESTAMENT = "NT"
TRANSLATION_STATE_WHOLE_BIBLE = "WB"
TRANSLATION_STATE_NO_SCRIPTURE = "NS"
TRANSLATION_STATE_NO_RECORD = "NR"
TRANSLATION_STATE_UNKNOWN_YEAR = -1

TRANSLATION_STATE_STATE_KEY = "TS"
TRANSLATION_STATE_YEAR_KEY = "YR"